### ISSUE TITLE
NPM module doesn't have license

### ISSUE THREAD

**Issue by craigbox** [armosec/vscode-kubescape#10]
vscode-kubescape uses an NPM module called [buffers](https://www.npmjs.com/package/buffers), which was published to GitHub over 10 years ago and was never updated. It does not contain a license.  I imagine this is an oversight, but I have been unable to contact the author and the [original repository](https://github.com/substack/node-buffers) has been deleted from GitHub.  

[FOSSA report](https://app.fossa.com/projects/git%2Bgithub.com%2Fkubescape%2Fvscode-kubescape/refs/branch/master/507e11540fc696ec06a3f7765fb3fffc4753d145/issues/licensing/522150)

I've [raised an issue with the vscode-test repo](https://github.com/microsoft/vscode-test/issues/197) also.

**Comment by craigbox** [comment]
This has been fixed upstream: future releases of vscode-test won't fail in this way.  Marking closed.

**Comment by connor4312** [comment]
This is now released in @vscode/test-electron@2.3.0

**Comment by craigbox** [comment]
Thanks @connor4312 !
